---
title: "Public Forum"
description: |
---

I believe that it is important for scholars to share their work with the broader reading public. While this type of writing is always important in order to maintain an engaged democratic citizenry, it is particularly important now given public skepticism about the value of academic research.

I have contributed articles on my research on the [electoral effects of North Carolina Commissioner of Labor Cherie Berry's elevator pictures](https://www.washingtonpost.com/news/monkey-cage/wp/2016/04/14/cherie-berry-put-her-picture-in-every-north-carolina-elevator-heres-how-that-affected-her-reelection/) and the [potential negative electoral and policy consequences to the president's party that stem from appointed an elected official to the Cabinet](https://www.washingtonpost.com/politics/2020/12/02/heres-problem-biden-faces-if-he-picks-current-lawmakers-his-cabinet/) (with Jonathan Spiegler and Aidan Floyd) in the *Monkey Cage*. 

I have also written pieces on the [electoral success of Black candidates in electorally competitive districts](https://theconversation.com/black-candidates-can-win-in-swing-districts-151980) and the [relative effectiveness of gun control laws and mental health care access in reducing gun violence](https://theconversation.com/more-mental-health-care-alone-will-not-stop-gun-violence-94201) (with Jonathan Spielger) for *The Conversation.* I also wrote a piece for *Sabato's Crystal Ball* on [what constitutes a congressional wave election](https://centerforpolitics.org/crystalball/articles/how-to-tell-if-2016-is-a-wave-election/).

