---
title: "Research"
description: |
---
My research focuses on legislative politics, elections, and policymaking. My book project, *Minority Party Misery* was published earlier this year by *University of Michigan Press*. My published work has also appeared in academic journals such as *Politics, Groups, and Identities* and *Policy Studies Journal*. Currently, I am working on a project on turnout in midterm elections with John Aldrich. My research with Jonathan Spiegler and Aidan Floyd on the electoral consequences of the appointment of elected officials to the U.S. Cabinet is forthcoming from the *Journal of Policy History*. My second book, *Waves of Discontent: Electoral Volatility, Public Policymaking, and the Health of American Democracy* is under advance contract with *University of Michigan Press* and my initial draft will be submitted to the Press this coming semester.

**Book ** 

[*Minority Party Misery: Political Powerlessness and Electoral Disengagement.*](https://www.press.umich.edu/11513516/minority_party_misery) 2021. Ann Arbor: University of Michigan Press.

**Abstract**: This book examines the role of minority party status on politicians’ engagement in electoral politics. Jacob Smith argues that politicians are more likely to be engaged in electoral politics when they expect their party to be in the majority in Congress after the next election and less likely when they anticipate their party will be in the minority. This effect is particularly likely to hold true in recent decades where parties disagree on a substantial number of issues. Politicians whose party will be in the majority have a clear incentive to engage in electoral politics because their preferred policies have a credible chance of passing if they are in the majority. In contrast, it is generally difficult for minority party lawmakers to get a hearing on—much less advance—their preferred policies, particularly when institutional rules inside Congress favor the majority party. Instead, minority party lawmakers spend most of their time fighting losing battles against policy proposals from the majority party. *Minority Party Misery* examines the consequences of the powerlessness that politicians feel from continually losing battles to the majority party in Congress. Its findings have important consequences for democratic governance, as highly qualified minority party politicians may choose to leave office due to their dismal circumstances rather than continue to serve until their party eventually reenters the majority.

**Recent Journal Articles**

["Just as electable: Black Democratic candidates in swing districts."](https://www.tandfonline.com/doi/full/10.1080/21565503.2020.1838302) 2020. *Politics, Groups, and Identities* Available Online First.

**Abstract**: Considerable debate exists in the literature about whether white voters are willing to support Black candidates for office, particularly in electorally competitive, non-majority minority districts. This paper leverages the 2018 congressional election – which saw six Black Democratic candidates win electorally competitive, majority white congressional districts – to contribute to this debate. Controlling for an array of congressional district-specific factors, I find that Black candidates performed no worse than white candidates did in swing seats. These results suggest that worries from party leaders that Black candidates cannot win in majority white swing districts may be overblown.

["Explaining Gun Deaths: Gun Control, Mental Illness, and Policymaking in the American States."](https://onlinelibrary.wiley.com/doi/abs/10.1111/psj.12242) (with Jonathan Spiegler) 2020. *Policy Studies Journal* 48(1):235-256.

**Abstract**: Seeking to test two commonly proposed solutions to gun deaths in the United States, we examine the extent to which (1) tougher gun control laws, (2) greater access to mental health services, and (3) a combination of both approaches affect the rate of gun deaths in American states. We find that tougher gun control laws, as well as a combination of both approaches, are associated with a lower overall rate of gun deaths, and with a lower rate of nonsuicide gun deaths, while only tougher gun control laws are significantly associated with a reduction in the rate of gun‐related suicides. Our findings serve as an initial guide to policymakers seeking to reduce the rate of gun deaths in their states.

**Connecting Research to Teaching**

- Jonathan Spiegler and I contributed a case study to SAGE's Research Methods Cases entitled ["Regression Analysis for Beginners: Exploring Gun Violence"](https://methods.sagepub.com/case/regression-analysis-for-beginners-exploring-gun-violence) based upon our research for the PSJ article. In this case study, we introduce the introductory undergraduate student to OLS regression through the window of the analysis we conducted for this paper.

- Previously, I wrote another [SAGE case study](Cherie Berry’s Elevator Pictures, Spatial Regression, and the Ups and Downs of the Research Process) on my and Neil Weinberg's 2016 [*American Politics Research*](https://journals.sagepub.com/doi/abs/10.1177/1532673X15602755) paper on the electoral effect of former North Carolina Commissioner of Labor Cherie Berry's elevator pictures. This case study was designed to introduce the advanced undergraduate students to spatial modeling.
