---
title: "Teaching"
description: |
---

My teaching interests include legislative politics, elections, undergraduate statistical methods, and academic writing. Currently, I am an Assistant Research Professor in the Departments of [Statistical Science](https://stat.duke.edu/) and [Political Science](https://polisci.duke.edu/) at Duke University. This coming semester I am teaching *STA101: Data Analysis and Statistical Inference* and *STA199: Introduction to Data Science and Statistical Thinking*. In the Spring, in addition to my statistics classes, I will be teaching *POLI 116: The American Political System* in the Political Science Department.

Previously, I taught courses in the [Thompson Writing Program](https://twp.duke.edu/) at Duke, and the UNC [Political Science Department](https://politicalscience.unc.edu/) and the [MPA@UNC](https://onlinempa.unc.edu/) program. Teaching is incredibly rewarding because it allows me to channel my expertise into guiding students’ educational journey. My classes are usually a mix of short lectures intertwined with other modes of learning, such as class-wide discussions, simulations, and activities that emphasize specific skills. I design my lectures to not be a one-sided conversation, but rather promote critical thought and provoke responses from students. I also incorporate active learning into my classes with simulations and discussions.

Here are sample syllabi from two of the courses I have taught:

- [**Statistics 101: Data Analysis and Statistical Inference**](https://github.com/jacobfhsmith/jacobfhsmith.github.io/blob/main/STA101Syllabus_JacobSmith.pdf?raw=true) Introduction to statistics as a science of understanding and analyzing data. Themes include data collection, exploratory analysis, inference, and modeling. Focus on principles underlying quantitative research in social sciences, humanities, and public policy. Research projects teach the process of scientific discovery and synthesis and critical evaluation of research and statistical arguments. Readings give perspective on why in 1950, S. Wilks said, "Statistical thinking will one day be as necessary a qualification for efficient citizenship as the ability to read and write."

- [**Writing 101 Congress and Quantitative Writing:**](https://github.com/jacobfhsmith/jacobfhsmith.github.io/blob/main/Writing101Syllabus_JacobSmith.pdf?raw=true) The American people widely view Congress to be a dysfunctional institution, with a 2013 Public Policy Polling poll rating Congress as less popular than cockroaches, root canals, and the band Nickelback. Yet despite this unpopularity, most members of Congress who seek reelection continue to win. In this course, we will look at how scholars explain puzzles about Congress such as this through writings including theoretical essays, descriptive analyses, and quantitative research articles.